#ifndef LEVEL_H
#define LEVEL_H

#define MAPOBJECT_ITEM_FLAG               0x8000
#define MAPOBJECT_TOP_RENDER_ENEMY_FLAG    0x4000
#define MAPOBJECT_BOTTOM_RENDER_ENEMY_FLAG 0x2000
#define MAPOBJECT_COIN                    (MAPOBJECT_ITEM_FLAG | ITEM_ANIM_COIN)

#define MAPOBJECT_TOP_RENDER_LEFT_RUN     (MAPOBJECT_TOP_RENDER_ENEMY_FLAG | ENEMY_ANIM_LEFT_RUN)
#define MAPOBJECT_BOTTOM_RENDER_LEFT_RUN   (MAPOBJECT_BOTTOM_RENDER_ENEMY_FLAG | ENEMY_ANIM_LEFT_RUN)

#define MAPOBJECT_TOP_RENDER_RIGHT_RUN     (MAPOBJECT_TOP_RENDER_ENEMY_FLAG | ENEMY_ANIM_RIGHT_RUN)
#define MAPOBJECT_BOTTOM_RENDER_RIGHT_RUN   (MAPOBJECT_BOTTOM_RENDER_ENEMY_FLAG | ENEMY_ANIM_RIGHT_RUN)

#define MAPOBJECT_TOP_RENDER_LEFT_SKATE     (MAPOBJECT_TOP_RENDER_ENEMY_FLAG | ENEMY_ANIM_LEFT_SKATE)
#define MAPOBJECT_BOTTOM_RENDER_LEFT_SKATE   (MAPOBJECT_BOTTOM_RENDER_ENEMY_FLAG | ENEMY_ANIM_LEFT_SKATE)

#define MAPOBJECT_TOP_RENDER_RIGHT_SKATE     (MAPOBJECT_TOP_RENDER_ENEMY_FLAG | ENEMY_ANIM_RIGHT_SKATE)
#define MAPOBJECT_BOTTOM_RENDER_RIGHT_SKATE   (MAPOBJECT_BOTTOM_RENDER_ENEMY_FLAG | ENEMY_ANIM_RIGHT_SKATE)

#define MAPOBJECT_TOP_RENDER_RIGHT_DRAGON (MAPOBJECT_TOP_RENDER_ENEMY_FLAG | ENEMY_ANIM_RIGHT_DRAGON)
#define MAPOBJECT_BOTTOM_RENDER_RIGHT_DRAGON (MAPOBJECT_BOTTOM_RENDER_ENEMY_FLAG | ENEMY_ANIM_RIGHT_DRAGON)


typedef struct {
  unsigned short background_tileAddresses[202][16];
  unsigned short item_spriteIds[202][16];
} level_t;

extern level_t level1;
extern level_t level;

#endif
